### ISSUE TITLE
newNr trebuie sa vina ca parametru. Numele nu ajuta... ia cauta unu mai bun

### ISSUE THREAD

**Issue by stefanbulzan** [cezarhre/homework#5]
https://github.com/cezarhre/homework/blob/f890e42605324ced1a8bd93a430fd2f2a737f8c0/src/SumInt.java#L36

**Comment by cezarhre** [comment]
Am schimbat denumirea...Am pus newNr deoarece era noul numar in afara array-ului cu care trebuiau comparate numerele din array
